version: "3.9"
services:
  b_agent:
    build:
      context: "build_agent"
      dockerfile: "Dockerfile"
    working_dir: /app
    volumes:
      - .:/app

  t_agent:
    build:
      context: "test_agent"
      dockerfile: "Dockerfile"
    working_dir: /app
    volumes:
      - .:/app
